# Generated by Django 4.0.6 on 2024-04-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='cursos',
            field=models.ManyToManyField(related_name='disciplinas', to='curso.curso'),
        ),
    ]
