# Generated by Django 4.0.6 on 2024-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_disciplina_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(max_length=100),
        ),
    ]
