# Generated by Django 4.0.6 on 2024-04-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_disciplina_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.areacientifica'),
        ),
    ]
