# Generated by Django 4.0.6 on 2024-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_alter_disciplina_area_cientifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ects',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='curso',
            name='num_semestres',
            field=models.IntegerField(default=6),
        ),
    ]
