# Generated by Django 4.0.6 on 2024-04-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_curso_ects_curso_num_semestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='apresentacao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='programa',
            field=models.TextField(default=''),
        ),
    ]
