# Generated by Django 4.0.6 on 2024-04-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='musicas_capas/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='ano_lancamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='albuns_capas/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bandas_fotos/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='informacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.IntegerField(blank=True, help_text='Duração em segundos', null=True),
        ),
    ]
