# Generated by Django 4.0.6 on 2024-04-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_banda_nacionalidade_musica_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='ano_criacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
