# Generated by Django 4.0.6 on 2024-04-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_banda_ano_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/albuns_capas/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/bandas_fotos/'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/musicas_capas/'),
        ),
    ]
