# Generated by Django 4.0.6 on 2024-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_alter_album_capa_alter_banda_foto_alter_musica_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='musica',
            name='capa',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
