# Generated by Django 4.0.6 on 2024-05-28 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artigos', '0005_alter_comentario_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='gostos',
            field=models.ManyToManyField(related_name='gostos', to=settings.AUTH_USER_MODEL),
        ),
    ]
