# Generated by Django 4.0.6 on 2024-06-03 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artigos', '0006_artigo_gostos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='gostos',
            field=models.ManyToManyField(blank=True, related_name='gostos', to=settings.AUTH_USER_MODEL),
        ),
    ]
